export default function sitemap() {
  const cities = [
    "roma",
    "milano",
    "napoli",
    "torino",
    "palermo",
    "genova",
    "bologna",
    "firenze",
    "bari",
    "catania",
    "venezia",
    "verona",
    "messina",
    "padova",
    "trieste",
    "taranto",
    "brescia",
    "prato",
    "parma",
    "modena",
    "reggio-calabria",
    "reggio-emilia",
    "perugia",
    "livorno",
    "ravenna",
    "cagliari",
    "foggia",
    "rimini",
    "salerno",
    "ferrara",
    "sassari",
    "latina",
    "monza",
    "siracusa",
    "pescara",
    "bergamo",
    "forli",
    "trento",
    "vicenza",
    "terni",
    "bolzano",
    "novara",
    "piacenza",
    "ancona",
    "arezzo",
    "udine",
    "cesena",
    "lecce",
    "la-spezia",
    "como",
    "lucca",
    "pisa",
    "treviso",
    "varese",
    "grosseto",
    "asti",
    "alessandria",
    "pavia",
    "mantova",
    "cosenza",
    "caserta",
    "brindisi",
    "potenza",
    "matera",
    "viterbo",
    "agrigento",
    "trapani",
    "ragusa",
    "crotone",
    "catanzaro",
    "cuneo",
    "imperia",
    "savona",
    "aosta",
    "belluno",
    "rovigo",
    "sondrio",
    "gorizia",
    "pordenone",
    "campobasso",
    "isernia",
    "benevento",
    "avellino",
    "chieti",
    "teramo",
    "laquila",
    "oristano",
    "nuoro",
    "olbia",
    "sanremo",
    "viareggio",
    "carrara",
    "fano",
    "pesaro",
    "senigallia",
    "civitanova-marche",
    "gallipoli",
    "riccione",
    "san-benedetto-del-tronto",
    "sorrento",
  ]

  return [
    {
      url: "https://droneguard.it",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/come-funziona",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/faq",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/contattaci",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/login",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/register",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/ispezioni-con-drone",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/trova-pilota-drone",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/termografia-con-drone",
      lastModified: new Date(),
    },
    {
      url: "https://droneguard.it/piloti-drone-certificati",
      lastModified: new Date(),
    },

    ...cities.map((city) => ({
      url: `https://droneguard.it/pilota-drone-${city}`,
      lastModified: new Date(),
    })),
  ]
}